superstore_dwh_advanced:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "post1616!"
      port: 5432
      dbname: superstore
      schema: public
      threads: 4
      keepalives_idle: 0
